import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head"; // Importujemy komponent Head
import Navigation from "@/components/Navigation";
import { Alumni_Sans_Pinstripe } from 'next/font/google';

const alumni = Alumni_Sans_Pinstripe({
  subsets: ['latin'], // Wybierz odpowiedni subset, jeśli potrzebujesz np. cyrylicy
  weight: ['400'],    // Wybierz różne wagi fontów, jeśli są potrzebne
  display: 'swap',    // Ustawienie display dla lepszej wydajności
});

export const metadata: Metadata = {
  title: "Świątynia Smaku Sushi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <Head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Alumni+Sans+Pinstripe:ital@0;1&display=swap" rel="stylesheet"/>
      </Head>
      <body className={alumni.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
